source "$XDG_CONFIG_HOME/zsh/aliases"

# random misc options
setopt AUTO_PARAM_SLASH
unsetopt CASE_GLOB

# additional autocompletions (from homebrew)
if type brew &>/dev/null; then
FPATH=$(brew --prefix)/share/zsh-completions:$FPATH

autoload -Uz compinit
compinit
fi

# syntax highlighting (homebrew)
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
# syntax highlighting (book)
#source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# autocompletion
autoload -Uz compinit; compinit

# autocomplete hidden files
_comp_options+=(globdots)
source ~/dotfiles/zsh/external/completion.zsh

fpath=($ZDOTDIR/external $fpath)

# bd
source ~/dotfiles/zsh/external/bd.zsh

# load prompt
autoload -Uz prompt_purification_setup; prompt_purification_setup

# push the current directory visited on to the stack
setopt AUTO_PUSHD
# do not store duplicate directories in the stack
setopt PUSHD_IGNORE_DUPS
# do not print the directory stack after using pushd or popd
setopt PUSHD_SILENT

alias d='dirs -v'
for index ({1..9}) alias "$index"="cd +${index}"; unset index

# vim-like stuff
bindkey -v
export KEYTIMEOUT=1
autoload -Uz cursor_mode && cursor_mode

zmodload zsh/complist
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history

# neovim specific stuff
autoload -Uz edit-command-line
zle -N edit-command-line
bindkey -M vicmd v edit-command-line

# fzf
# auto generated by homebrew
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# custom scripts
source $DOTFILES/zsh/scripts.sh

